export const countryToNationality = {
    US: 'American',
    GB: 'British',
    JP: 'Japanese',
    FR: 'French',
    DE: 'German',
    IN: 'Indian',
    CN: 'Chinese',
    BR: 'Brazilian',
    RU: 'Russian',
    CA: 'Canadian',
    AU: 'Australian',
    IT: 'Italian',
    ES: 'Spanish',
    MX: 'Mexican',
    KR: 'South Korean',
    ZA: 'South African',
    NG: 'Nigerian',
    EG: 'Egyptian',
    TR: 'Turkish',
    SA: 'Saudi Arabian',
    AR: 'Argentinian',
    CL: 'Chilean',
    CO: 'Colombian',
    PE: 'Peruvian',
    VE: 'Venezuelan',
    SE: 'Swedish',
    NO: 'Norwegian',
    FI: 'Finnish',
    DK: 'Danish',
    NL: 'Dutch',
    BE: 'Belgian',
    CH: 'Swiss',
    AT: 'Austrian',
    PT: 'Portuguese',
    GR: 'Greek',
    PL: 'Polish',
    CZ: 'Czech',
    HU: 'Hungarian',
    RO: 'Romanian',
    BG: 'Bulgarian',
    HR: 'Croatian',
    RS: 'Serbian',
    SK: 'Slovak',
    SI: 'Slovenian',
    UA: 'Ukrainian',
    BY: 'Belarusian',
    KZ: 'Kazakh',
    UZ: 'Uzbek',
    AZ: 'Azerbaijani',
    GE: 'Georgian',
    AM: 'Armenian',
    IL: 'Israeli',
    IR: 'Iranian',
    IQ: 'Iraqi',
    SY: 'Syrian',
    LB: 'Lebanese',
    JO: 'Jordanian',
    KW: 'Kuwaiti',
    QA: 'Qatari',
    AE: 'Emirati',
    OM: 'Omani',
    YE: 'Yemeni',
    PK: 'Pakistani',
    BD: 'Bangladeshi',
    LK: 'Sri Lankan',
    MM: 'Burmese',
    TH: 'Thai',
    MY: 'Malaysian',
    SG: 'Singaporean',
    ID: 'Indonesian',
    PH: 'Filipino',
    VN: 'Vietnamese',
    KH: 'Cambodian',
    LA: 'Laotian',
    MN: 'Mongolian',
    NZ: 'New Zealander',
    FJ: 'Fijian',
    PG: 'Papua New Guinean',
    SB: 'Solomon Islander',
    VU: 'Ni-Vanuatu',
    NC: 'New Caledonian',
    PF: 'French Polynesian',
    WS: 'Samoan',
    TO: 'Tongan',
    TV: 'Tuvaluan',
    KI: 'I-Kiribati',
    NR: 'Nauruan',
    MH: 'Marshallese',
    FM: 'Micronesian',
    PW: 'Palauan',
    TL: 'Timorese',
    BT: 'Bhutanese',
    NP: 'Nepalese',
    MV: 'Maldivian',
    AF: 'Afghan',
    TJ: 'Tajik',
    TM: 'Turkmen',
    KG: 'Kyrgyz',
    UY: 'Uruguayan',
    PY: 'Paraguayan',
    BO: 'Bolivian',
    EC: 'Ecuadorian',
    GY: 'Guyanese',
    SR: 'Surinamese',
    GF: 'French Guianese',
    BZ: 'Belizean',
    GT: 'Guatemalan',
    HN: 'Honduran',
    SV: 'Salvadoran',
    NI: 'Nicaraguan',
    CR: 'Costa Rican',
    PA: 'Panamanian',
    CU: 'Cuban',
    HT: 'Haitian',
    DO: 'Dominican',
    JM: 'Jamaican',
    TT: 'Trinidadian',
    BB: 'Barbadian',
    LC: 'Saint Lucian',
    VC: 'Vincentian',
    GD: 'Grenadian',
    AG: 'Antiguan',
    DM: 'Dominican (Dominica)',
    KN: 'Kittitian',
    BS: 'Bahamian',
    BZ: 'Belizean',
    KY: 'Caymanian',
    BM: 'Bermudian',
    VG: 'Virgin Islander',
    TC: 'Turks and Caicos Islander',
    MS: 'Montserratian',
    AI: 'Anguillan',
    MF: 'Saint-Martinois',
    SX: 'Sint Maartener',
    CW: 'Curaçaoan',
    AW: 'Aruban',
    BQ: 'Bonairean',
    SX: 'Sint Eustatian',
    Saba: 'Saban',
    GP: 'Guadeloupean',
    MQ: 'Martiniquais',
    GF: 'French Guianese',
    RE: 'Réunionese',
    YT: 'Mahoran',
    PM: 'Saint-Pierrais',
    WF: 'Wallisian',
    PF: 'French Polynesian',
    NC: 'New Caledonian',
    TF: 'French Southern and Antarctic Lands',
    IO: 'British Indian Ocean Territory',
    PN: 'Pitcairn Islander',
    GS: 'South Georgia and the South Sandwich Islands',
    AQ: 'Antarctic',
    BV: 'Bouvet Islander',
    HM: 'Heard Island and McDonald Islands',
    UM: 'United States Minor Outlying Islands',
    CX: 'Christmas Islander',
    CC: 'Cocos Islander',
    NF: 'Norfolk Islander',
    TK: 'Tokelauan',
    NU: 'Niuean',
    CK: 'Cook Islander',
    AS: 'American Samoan',
    GU: 'Guamanian',
    MP: 'Northern Marianan',
    PR: 'Puerto Rican',
    VI: 'Virgin Islander (U.S.)',
    UM: 'United States Minor Outlying Islands',
    FM: 'Micronesian',
    MH: 'Marshallese',
    PW: 'Palauan',
    KI: 'I-Kiribati',
    NR: 'Nauruan',
    TV: 'Tuvaluan',
    WS: 'Samoan',
    TO: 'Tongan',
    VU: 'Ni-Vanuatu',
    FJ: 'Fijian',
    NC: 'New Caledonian',
    PF: 'French Polynesian',
    TK: 'Tokelauan',
    NU: 'Niuean',
    CK: 'Cook Islander',
    WS: 'Samoan',
    TO: 'Tongan',
    TV: 'Tuvaluan',
    KI: 'I-Kiribati',
    NR: 'Nauruan',
    MH: 'Marshallese',
    FM: 'Micronesian',
    PW: 'Palauan',
    TL: 'Timorese',
    BT: 'Bhutanese',
    NP: 'Nepalese',
    MV: 'Maldivian',
    AF: 'Afghan',
    TJ: 'Tajik',
    TM: 'Turkmen',
    KG: 'Kyrgyz',
    UY: 'Uruguayan',
    PY: 'Paraguayan',
    BO: 'Bolivian',
    EC: 'Ecuadorian',
    GY: 'Guyanese',
    SR: 'Surinamese',
    GF: 'French Guianese',
    BZ: 'Belizean',
    GT: 'Guatemalan',
    HN: 'Honduran',
    SV: 'Salvadoran',
    NI: 'Nicaraguan',
    CR: 'Costa Rican',
    PA: 'Panamanian',
    CU: 'Cuban',
    HT: 'Haitian',
    DO: 'Dominican',
    JM: 'Jamaican',
    TT: 'Trinidadian',
    BB: 'Barbadian',
    LC: 'Saint Lucian',
    VC: 'Vincentian',
    GD: 'Grenadian',
    AG: 'Antiguan',
    DM: 'Dominican (Dominica)',
    KN: 'Kittitian',
    BS: 'Bahamian',
    BZ: 'Belizean',
    KY: 'Caymanian',
    BM: 'Bermudian',
    VG: 'Virgin Islander',
    TC: 'Turks and Caicos Islander',
    MS: 'Montserratian',
    AI: 'Anguillan',
    MF: 'Saint-Martinois',
    SX: 'Sint Maartener',
    CW: 'Curaçaoan',
    AW: 'Aruban',
    BQ: 'Bonairean',
    SX: 'Sint Eustatian',
    Saba: 'Saban',
    GP: 'Guadeloupean',
    MQ: 'Martiniquais',
    GF: 'French Guianese',
    RE: 'Réunionese',
    YT: 'Mahoran',
    PM: 'Saint-Pierrais',
    WF: 'Wallisian',
    PF: 'French Polynesian',
    NC: 'New Caledonian',
    TF: 'French Southern and Antarctic Lands',
    IO: 'British Indian Ocean Territory',
    PN: 'Pitc'
}
